version: "3.8"

services:
  postgres:
    container_name: fa-test-postgres
    image: postgres:13.4
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fusionauth:
    container_name: fa-test-fusionauth
    image: fusionauth/fusionauth-app:1.35.0
    environment:
      DATABASE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: ${FUSION_AUTH_URL}
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
      SEARCH_SERVERS: ${ELASTIC_ENDPOINT}
      SEARCH_TYPE: elasticsearch

      # Kickstart Configurations
      FUSIONAUTH_ACCESS_TOKEN_KEY_ID: ${FUSIONAUTH_ACCESS_TOKEN_KEY_ID}
      FUSIONAUTH_ADMIN_APPLICATION_ID: ${FUSIONAUTH_ADMIN_APPLICATION_ID}
      FUSIONAUTH_ADMIN_EMAIL: ${FUSIONAUTH_ADMIN_EMAIL}
      FUSIONAUTH_ADMIN_ID: ${FUSIONAUTH_ADMIN_ID}
      FUSIONAUTH_ADMIN_PASSWORD: ${FUSIONAUTH_ADMIN_PASSWORD}
      FUSIONAUTH_ADMIN_USERNAME: ${FUSIONAUTH_ADMIN_USERNAME}
      FUSIONAUTH_API_KEY: ${FUSIONAUTH_API_KEY}
      FUSIONAUTH_AUTH_APPLICATION_ID: ${FUSIONAUTH_AUTH_APPLICATION_ID}
      FUSIONAUTH_AZURE_DOMAIN: ${FUSIONAUTH_AZURE_DOMAIN}
      FUSIONAUTH_IDENTITY_PROVIDER_ID: ${FUSIONAUTH_IDENTITY_PROVIDER_ID}
      FUSIONAUTH_ID_TOKEN_KEY_ID: ${FUSIONAUTH_ID_TOKEN_KEY_ID}
      FUSIONAUTH_INGEST_APPLICATION_ID: ${FUSIONAUTH_INGEST_APPLICATION_ID}
      FUSIONAUTH_LAMBDA_ID: ${FUSIONAUTH_LAMBDA_ID}
      FUSIONAUTH_LAMBDA_OPENID_RECONCILE_ID: ${FUSIONAUTH_LAMBDA_OPENID_RECONCILE_ID}
      FUSIONAUTH_OAUTH_AUTH_ENDPOINT: ${FUSIONAUTH_OAUTH_AUTH_ENDPOINT}
      FUSIONAUTH_OAUTH_TOKEN_ENDPOINT: ${FUSIONAUTH_OAUTH_TOKEN_ENDPOINT}
      FUSIONAUTH_OAUTH_USERINFO_ENDPOINT: ${FUSIONAUTH_OAUTH_USERINFO_ENDPOINT}
      FUSIONAUTH_OAUTH_CLIENT_ID: ${FUSIONAUTH_OAUTH_CLIENT_ID}
      FUSIONAUTH_OAUTH_SECRET: ${FUSIONAUTH_OAUTH_SECRET}
      FUSIONAUTH_TENANT_ID: ${FUSIONAUTH_TENANT_ID}
      FUSIONAUTH_THEME_ID: ${FUSIONAUTH_THEME_ID}
      FUSIONAUTH_VERUS_APPLICATION_ID: ${FUSIONAUTH_VERUS_APPLICATION_ID}
      VERUS_ADMIN_EMAIL: ${VERUS_ADMIN_EMAIL}
      VERUS_ADMIN_ID: ${VERUS_ADMIN_ID}
      VERUS_ADMIN_PASSWORD: ${VERUS_ADMIN_PASSWORD}
      VERUS_ADMIN_USERNAME: ${VERUS_ADMIN_USERNAME}
      VERUS_ADMIN_URL: ${VERUS_ADMIN_URL}
      VERUS_AUTH_URL: ${VERUS_AUTH_URL}
      VERUS_INGEST_URL: ${VERUS_INGEST_URL}
      VERUS_URL: ${VERUS_URL}
    depends_on:
      - elasticsearch
      - postgres
    ports:
      - 29011:9011
    volumes:
      - fusionauth-config:/usr/local/fusionauth/config
      - ./priv/data/fusionauth:/usr/local/fusionauth/kickstart

  elasticsearch:
    container_name: fa-test-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - node.name=elasticsearch-01
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ports:
      - 29200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.2.0/24

volumes:
  postgres-data:
  fusionauth-config:
  elasticsearch-data:
