name: "Cache restoration"
description: "Setup an Elixir environment and restore cache if any, given OTP and Elixir versions"

inputs:
  elixir-version:
    description: "Elixir version to use, default to 1.13.0"
    required: true
    default: "1.13.0"
  otp-version:
    description: "OTP Version to use, default to 24.2"
    required: true
    default: "24.2"
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.mix-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup elixir ${{ inputs.elixir-version }}
      uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}

    - name: Cache mix dependencies
      id: mix-cache
      uses: actions/cache@v2
      with:
        path: |
          _build
          deps
        key: mix-dependencies-${{ hashFiles('mix.lock') }}
