name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: ./.github/actions/cache-restore
        id: cache-mix-dependencies
        with:
          elixir-version: "1.13.0"
          otp-version: "24.2"

      - name: Install mix dependencies if cache is empty
        if: steps.cache-mix-dependencies.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache-restore
        id: cache-mix-dependencies
        with:
          elixir-version: "1.13.0"
          otp-version: "24.2"
      - name: Build the stack
        run: |
          touch .env
          cp .env.example .env
          source .env
          ./run coveralls
